### ISSUE TITLE
Typing 'cancelled' when using company completion

### ISSUE THREAD

**Issue by Zulu-Inuoe** [joaotavora/sly#209]
I've been trying to figure this out for a while now, but I wanted to note it for posterity (if only for me in the future).

Company is configured with `company-idle-delay` set to 0 for instant completion.
When at the sly repl, typing `cl:simple-array` at a reasonable typing speed results in multiple `Quit` events in the `*Messages*` buffer, and at the repl I'm left with the input `cl:siple-aray` or like.

I'm trying to debug what is going on with this but have yet been unsuccessful. Setting up `debug-on-quit` gives me an empty backtrace for the quit events, so I do not yet know if this is a sly issue, a company issue, or a company-capf issue.

However, company completion on elisp works without any issues

Thanks.

Software:
Emacs 26.1, Windows 10 x64, SBCL 1.4.12

**Comment by Zulu-Inuoe** [comment]
On a fresh (non-bloated) emacs install, this is much less likely to occur. So I found it difficult to trigger on a barebones Emacs+Sly+Company, but it still happens.
Adding `company-quickhelp` into the mix will make it much easier to trigger

**Comment by joaotavora** [comment]
I've seen these kinds of problems, too.  Thanks for the recipe. I'll have a look.

**Comment by joaotavora** [comment]
And it's likely a bug.

**Comment by joaotavora** [comment]
@Zulu-Inuoe, can you check if I have fixed it with my latest commit?

**Comment by Zulu-Inuoe** [comment]
@joaotavora Thank you -so much- for looking into this. That works much better now. I had to take a break from looking at it as I didn't get very far after spending a lot of time at it.

However, even after those last two commits, I'm still seeing the same behaviour in #210 unfortunately.
Well, at least the random cancellation.
